version: 2.1
jobs:
  build:
    working_directory: ~/robot
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.3.4
      TZ: Asia/Tokyo
      JVM_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256m
    steps:
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt
            apt-get clean && apt-get autoclean
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          name: clean
          command: cat /dev/null | sbt clean
      - run:
          name: compile
          command: cat /dev/null | sbt test:compile
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - run:
          name: coverage
          command: cat /dev/null | sbt coverage
      - run:
          name: coverage report
          command: cat /dev/null | sbt coverageReport